station:
  # if the station position can't be found in the obs header, manually input it here
  info: [NULL, NULL, NULL]
rinex:
  singlefile:
    observation:
      - .\observation\NOME1190_rnx2.25O
    navigation:
      - .\navigation\NOME1190.25P
  output_dir: .\output
  multiday: # options for multiday process
    enabled: false # if true, it will read obs_location directory and try to process all data
  obs_size_threshold: 80
constellations:
  - G
  - R
  - E
  - C
etc:
  disable_progress_bar: false
  disable_logging: false
  disable_parallel: false